### ISSUE TITLE
If dataDir is misconfigured, there is no way to login to adjust it

### ISSUE THREAD

**Issue by stephenlawrence** [opendocman/opendocman#166]
If a user is moving sites to a new server and their dataDir path changes, when they go to login @ their new site the dataDir warning will show and will keep re-directing them to the login. The only way they would be able to get past this is to manually adjust the mysql data.

**Comment by johncarn** [comment]
I was able to adjust this by replacing the entry in the mysql database directly. I had the wrong format for the dataDir and had to change it. Took about 3 minutes. Don't have the exact sql statement in front of me at the moment, but can get it for you if you need it.

**Comment by katedev** [comment]
johncarn,
 It will be helpful iff you share with us what exactly in the database I need to edit. I laso would wish to accomplish that in 3 minutes

**Comment by johncarn** [comment]
This should work for you. I'll show syntax using my database name.

You need to go to the mysql console. Once you are there, use the following commands:

Use opendocman_db; 
(substitute your database name)

select * from odm_settings;
(the output should have a line that has a value in the name column of datadir, and the value column of the locationof the file repository)

delete from `odm_settings` where name = datadir;
(this should delete the existing line that you have for datadir. You may need quotes after the where clause , i.e. 'name=datadir'  I don't have the exact syntax in front of me

Insert Into `odm_settings` values (null, 'datadir', '/var/www/document_repository/', 'location of file repository. This should ideally be outside the Web server root. Make sure the server has permissions to read/write files to this folder!. (Examples: Linux - /var/www/document/repository/  :  Windows - c:/document_repository/', 'maxsize=255');
(this statement, from 'location of file repository.....toc:/document_repository/', is a comment field. It shows the exact syntax you need to use. Note the use of the left tilted single quote vs. single quote, and also the forward slashes in the syntax for windows, vs. backward slashes. the third value in the paren after values is what you need to change for your site. It defaults to 'var/www/document_repository/'    Change that for your site and hit enter. Also notice how the statements end in ;)

This SQL statement is right out of the database.sql file that comes with opendocman installation files. 

Hopefully this helps. If you have troubles with the syntax, let me know. I'll provide the commands to delete the entire table, re-create it and insert all the data you need.

To verify you got the line right, use the Select statement at the top of this post.

jc
