### ISSUE TITLE
I get this error when trying to upload documents.

### ISSUE THREAD

**Issue by jpcreek** [opendocman/opendocman#196]
Deprecated: preg_replace(): The /e modifier is deprecated, use preg_replace_callback instead in C:\wamp\www\opendocman\includes\smarty\Smarty_Compiler.class.php on line 270
Call Stack
#	Time	Memory	Function	Location
1	0.0008	314008	{main}( )	..\details.php:0
2	0.0439	2703312	display_smarty_template( )	..\details.php:256
3	0.0439	2703432	Smarty->display( )	..\functions.php:809
4	0.0439	2703576	Smarty->fetch( )	..\Smarty.class.php:1106
5	0.0440	2703872	Smarty->_compile_resource( )	..\Smarty.class.php:1254
6	0.0446	2717056	Smarty->_compile_source( )	..\Smarty.class.php:1422
7	0.0484	3402824	Smarty_Compiler->_compile_file( )	..\Smarty.class.php:1489
8	0.0485	3408896	preg_replace ( )	..\Smarty_Compiler.class.php:270

**Comment by stephenlawrence** [comment]
What version of PHP are you running?

**Comment by jpcreek** [comment]
5.5.12

Thank You,

James Creekmore
Chief Consultant
CreekNET Solutions, LLC
(859) 414-6565
jpcreek@creeknetsolutions.com

This message, including attachments, is intended only for the person(s) or
entity to which it is addressed and may contain information that is
privileged, confidential, and exempt from disclosure under applicable law.
If the reader of this message is not the intended recipient, you are hereby
notified that any dissemination, distribution, or copying of this
communication is strictly prohibited by law.

**Comment by stephenlawrence** [comment]
Looks like Smarty has an update for that issue. Updating the smarty lib.
