### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by bibaowen** [opendocman/opendocman#198]
Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[HY093]: Invalid parameter number: number of bound variables does not match number of tokens' in /homepages/41/d423617433/htdocs/trelcorp/opendocman/search.php:214 Stack trace: #0 /homepages/41/d423617433/htdocs/trelcorp/opendocman/search.php(214): PDOStatement->execute() #1 /homepages/41/d423617433/htdocs/trelcorp/opendocman/search.php(245): search('author', 'owen rosie', 'on', NULL, Array) #2 {main} thrown in /homepages/41/d423617433/htdocs/trelcorp/opendocman/search.php on line 214

**Comment by stephenlawrence** [comment]
exact phrase author search was not using the correct prepared statement parameters.

**Comment by bibaowen** [comment]
Does this mean that 1.3.2 will be released sooner?
