### ISSUE TITLE
Invalid index in index.php version 1.3.2

### ISSUE THREAD

**Issue by Jaybus2** [opendocman/opendocman#200]
Version: 1.3.2
File: index.php

Invalid index PHP error at lines 131 and 132.

Line 131:
     Current:  $username = $result['username'];
     Should be: $username = $result[0]['username'];

Line 132:
     Current:  $password = $result['password'];
     Should be:  $password = $result[0]['password'];

**Comment by stephenlawrence** [comment]
Those values are not used. Removed them.
