### ISSUE TITLE
Partial Upload of Documents

### ISSUE THREAD

**Issue by PhattMattSlimm** [opendocman/opendocman#205]
I'm attempting to add pdf files to ODM and, more often than not, the additions/uploads are not successful. I'm regularly encountering a scenario where files are not wholly uploaded to ODM, but ODM is reporting the document as a successful upload.
As an example, earlier today I attempted to upload a 4Mb PDF. Upon filling in the details and browsing for the file, the File Detail screen reports a successful upload with a file size of only 172Kb. I have tried the following to no avail:
* Trying to upload the same file through different browsers;
* Testing on different pdf files;
* Logging out and back into ODM.

I've attempted to open the file [to test whether it's file size miscommunication] and, indeed, the file will not open.

I'm not familiar with PHP but am happy to assist in resolving the issue through testing and troubleshooting :)

**Comment by PhattMattSlimm** [comment]
I am running v1.3.2

**Comment by stephenlawrence** [comment]
HI @PhattMattSlimm, I know its been a while but I was curious if you resolved your issues. This seems like a server related issue to me. There may be something in your php error logs, if not, I would check with the hosting provider for more details.

**Comment by stephenlawrence** [comment]
Closing this since its been a while.
