### ISSUE TITLE
Unable to see recently uploaded documents

### ISSUE THREAD

**Issue by KosSemonski** [opendocman/opendocman#211]
OpenDocMan limits the startup query to 500 records.
When there are more than 500 records, the main screen shows only the FIRST 500 records.
Therefore, records 501, 502, 503, etc. are not visible in the query
If you sort descending, the query does not re-query the data set from the end of the list of files.  

The search feature DOES NOT support a search by FILE NUMBER RANGE

So, you will NEVER be able to browse recently uploaded files AFTER you have added 500 files to the database.

The query should re-post when sorting, OR, there should be a search feature to define the file numbers to display in the search result.

**Comment by stephenlawrence** [comment]
You can adjust the max_query value as high as you would like. The 500 was just a default (and stopgap fix).
