### ISSUE TITLE
Problemas con la Aplicacion

### ISSUE THREAD

**Issue by Ctians** [opendocman/opendocman#218]
Al instalar la aplicacion correctamente siguiento paso a paso la instalacion, al acceder a la interfaz de logueo, el tema que trae por defecto no se aplica y al registrarme con mi usuario y clave, al menu se le va su estilo de presentacion y queda de forma html, tambien me da un error al acceder al menu de esa manera ya que dice que da un error con la url de la pagina. El opendocman que utilizo es la ultima version v1.3.4 estable en LINUX. quisiera ayuda con el problema que presento gracias.

**Comment by stephenlawrence** [comment]
Hello,

Not sure if the my translation is ok, but do you have php running on your web server?

**Comment by Ctians** [comment]
Hello good stephen PHP is installed and running, my server has apache and mysql php5. he makes the perfect installation, the problem occurs when you view the logging interface that does not have any presentation style and loguearme to the main menu page vertically without leave me like my style login page. thank you

**Comment by Ctians** [comment]
google translator is not good I hope you understand me

**Comment by stephenlawrence** [comment]
Please check your php error and see if anything is showing up there.

**Comment by Ctians** [comment]
![opendocman1](https://cloud.githubusercontent.com/assets/14113949/9667818/f89b4bae-5247-11e5-8146-7b670f9d6714.png)
![opendocman2](https://cloud.githubusercontent.com/assets/14113949/9667819/f89b6062-5247-11e5-8faf-c00529ba0c3c.png)
These are the capture and showing me how the interface.I OpenDocMan access my ip address for my Linux server.

**Comment by stephenlawrence** [comment]
Check your baseUrl setting in the Admin->Site Settings page (or directly in the database inside the odm_settings table. Make sure the baseUrl is pointing to http://192.168.23.15/opendocman

**Comment by Ctians** [comment]
perfecto stephen muchas gracias, ya solucionado
