### ISSUE TITLE
This file cannot be uploaded properly

### ISSUE THREAD

**Issue by satwindermatharu** [opendocman/opendocman#221]
Sir

when i upload the text, pdf files system display the error. "This file cannot be uploaded properly" and there is error no 18 which is listed in error.php. I had also check the extensions too

**Comment by stephenlawrence** [comment]
This message is displayed when the uploaded file is not present in the temporary upload folder on the server. You may have a PHP error in your logs. You may also want to verify that your php.ini settings point to a valid directory with the proper permissions.
