### ISSUE TITLE
Add Tamil language

### ISSUE THREAD

**Issue by stephenlawrence** [opendocman/opendocman#233]

**Comment by apmuthu** [comment]
This is just a set of 2 files:
https://github.com/apmuthu/opendocman/blob/master/includes/language/tamil.php
and
https://github.com/apmuthu/opendocman/blob/master/includes/language/DataTables/datatables.tamil.txt

Whilst the former was added and then edited in another commit, the latter was just added in one commit.

You can cherry pick the commits for this.

**Comment by apmuthu** [comment]
Thanks!
