### ISSUE TITLE
Unreadable content for word and excel 2013 xlsx and docx

### ISSUE THREAD

**Issue by JoopK** [opendocman/opendocman#257]
Word is able to recover, excel not.
Installed:
App Version: 1.3.5
Database Version: 1.2.8
Tried on chome and IE, no difference, see attachment.
[Unreadable office documents.docx](https://github.com/opendocman/opendocman/files/670064/Unreadable.office.documents.docx)

**Comment by JoopK** [comment]
When comparing the .dat file and the downloaded xlsx file I see the xlsx file has an additional initial 20 (hex):
1.dat
0000 0000: 20 50 4B 03 04 14 00 06  00 08 00 00 00 21 00 41   PK..... .....!.A
0000 0010: 37 82 CF 6E 01 00 00 04  05 00 00 13 00 08 02 5B  7é╧n.... .......[
0000 0020: 43 6F 6E 74 65 6E 74 5F  54 79 70 65 73 5D 2E 78  Content_ Types].x
0000 0030: 6D 6C 20 A2 04 02 28 A0  00 02 00 00 00 00 00 00  ml ó..(á ........
0000 0040: 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  ........ ........
0000 0050: 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  ........ ........
0000 0060: 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  ........ ........
0000 0070: 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  ........ ........
0000 0080: 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  ........ ........
0000 0090: 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  ........ ........
0000 00A0: 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  ........ ........
0000 00B0: 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  ........ ........
1.xlsx
0000 0000: 20 20 50 4B 03 04 14 00  06 00 08 00 00 00 21 00    PK.... ......!.
0000 0010: 41 37 82 CF 6E 01 00 00  04 05 00 00 13 00 08 02  A7é╧n... ........
0000 0020: 5B 43 6F 6E 74 65 6E 74  5F 54 79 70 65 73 5D 2E  [Content _Types].
0000 0030: 78 6D 6C 20 A2 04 02 28  A0 00 02 00 00 00 00 00  xml ó..( á.......
0000 0040: 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  ........ ........
0000 0050: 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  ........ ........
0000 0060: 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  ........ ........
0000 0070: 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  ........ ........
0000 0080: 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  ........ ........
0000 0090: 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  ........ ........
0000 00A0: 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  ........ ........
0000 00B0: 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  ........ ........

**Comment by maui1911** [comment]
I have this same problem :(

**Comment by logicalarts** [comment]
Can you download the .dat file to your local computer manually, then rename it to .xlsx? Or is that what you did?

**Comment by maui1911** [comment]
If I do that, the file binary the same as the original file I uploaded.

The extra hex char space (20) only gets added when downloading or viewing from the opendocman webinterface.

**Comment by logicalarts** [comment]
Can you duplicate this issue on our Demo site?

**Comment by maui1911** [comment]
text compare
![image](https://cloud.githubusercontent.com/assets/1742072/21820647/d6890614-d770-11e6-8658-ef40a7c2c377.png)

hex compare
![image](https://cloud.githubusercontent.com/assets/1742072/21820676/efe063be-d770-11e6-941e-652626b72a4a.png)

**Comment by logicalarts** [comment]
@maui1911 have you modified the code at all or is this 100% original code?

**Comment by JoopK** [comment]
Indeed 100% original code, and after setting language to english, problem solved....
@maui1911 how did you know I have a dutch site?

**Comment by JoopK** [comment]
view: http://files.groenlinksdelft.nl/view_file.php?submit=view&id=2&mimetype=application%2Fvnd.openxmlformats-officedocument.wordprocessingml.document
view_file.php:
getName(); $file_id = $file_obj->getId(); $realname = $file_obj->getName(); // Get the suffix of the file so we can look it up // in the $mimetypes array $suffix = ''; if (strchr($realname, '.')) { // Fix by blackwes $prefix = (substr($realname, 0, (strrpos($realname, ".")))); $suffix = strtolower((substr($realname, ((strrpos($realname, ".")+1))))); } // If we have a revision ID lets use the original // request id that included the file id and revision number (ex. 1_0) if (isset($revision_id)) { $file_id = $request_id; } $mimetype = File::mime_by_ext($suffix); $GLOBALS['smarty']->assign('mimetype', $mimetype); $GLOBALS['smarty']->assign('file_id', $file_id); // drw form display_smarty_template('view_file.tpl'); draw_footer(); } elseif ($_GET['submit'] == 'view') { $file_obj = new FileData($_REQUEST['id'], $pdo); // Added this check to keep unauthorized users from downloading - Thanks to Chad Bloomquist checkUserPermission($_REQUEST['id'], $file_obj->READ_RIGHT, $file_obj); $realname = $file_obj->getName(); if (isset($revision_id)) { $filename = $revision_dir . $request_id . ".dat"; } elseif ($file_obj->isArchived()) { $filename = $GLOBALS['CONFIG']['archiveDir'] . $_REQUEST['id'] . ".dat"; } else { $filename = $GLOBALS['CONFIG']['dataDir'] . $_REQUEST['id'] . ".dat"; } if (file_exists($filename)) { // send headers to browser to initiate file download header('Content-Length: '.filesize($filename)); // Pass the mimetype so the browser can open it header('Cache-control: private'); header('Content-Type: ' . $_GET['mimetype']); header('Content-Disposition: attachment; filename="' . rawurlencode($realname) . '"'); // Apache is sending Last Modified header, so we'll do it, too $modified=filemtime($filename); header('Last-Modified: '. date('D, j M Y G:i:s T', $modified)); // something like Thu, 03 Oct 2002 18:01:08 GMT readfile($filename); AccessLog::addLogEntry($_REQUEST['id'], 'V', $pdo); } else { echo msg('message_file_does_not_exist'); } } elseif ($_GET['submit'] == 'Download') { $file_obj = new FileData($_REQUEST['id'], $pdo); // Added this check to keep unauthorized users from downloading - Thanks to Chad Bloomquist checkUserPermission($_REQUEST['id'], $file_obj->READ_RIGHT, $file_obj); $realname = $file_obj->getName(); if (isset($revision_id)) { $filename = $revision_dir . $request_id . ".dat"; } elseif ($file_obj->isArchived()) { $filename = $GLOBALS['CONFIG']['archiveDir'] . $_REQUEST['id'] . ".dat"; } else { $filename = $GLOBALS['CONFIG']['dataDir'] . $_REQUEST['id'] . ".dat"; } if (file_exists($filename)) { // send headers to browser to initiate file download header('Cache-control: private'); header('Content-Type: '.$_GET['mimetype']); header('Content-Disposition: attachment; filename="' . $realname . '"'); header('Cache-Control: must-revalidate, post-check=0, pre-check=0'); header('Pragma: public'); readfile($filename); AccessLog::addLogEntry($_REQUEST['id'], 'D', $pdo); } else { echo msg('message_file_does_not_exist'); } } else { echo msg('message_nothing_to_do'); }

**Comment by maui1911** [comment]
@JoopK Joop, Why did you close this issue, did you change anything in the view_file.php?

Just because we found a source of the problem doesn't mean I don't want it to be fixed :) The users of my opendocman installation really want to use Dutch language.

**Comment by JoopK** [comment]
Hi,

 

I think I closed it by accident, you can reopen if you want.

For me the solution to use the English language is fine for the moment.

 

Thanks for your mail.

 

Regards,

 

Joop

 

Van: maui1911 [mailto:notifications@github.com] 
Verzonden: woensdag 11 januari 2017 08:06
Aan: opendocman/opendocman <opendocman@noreply.github.com>
CC: JoopK <joop.kunst@gmail.com>; Mention <mention@noreply.github.com>
Onderwerp: Re: [opendocman/opendocman] Unreadable content for word and excel 2013 xlsx and docx (#257)

 

@JoopK <https://github.com/JoopK>  Joop, Why did you close this issue, did you change anything in the view_file.php?

Just because we found a source of the problem doesn't mean I don't want it to be fixed :) The users of my opendocman installation really want to use Dutch language.

**Comment by stephenlawrence** [comment]
Ok, maybe there is a translated string in the Dutch file that is causing an issue. Let me take a look.

**Comment by sekerier** [comment]
The problem lies in the ./includes/language/dutch.php file. That contains a single whitespace *before* the php tag. That causes the downloaded/viewed document to have one additional whitespace before the actual content (as anything before the php tag will show up on the output) and most (binary) formats will get corrupted by that. 

Removing the whitespace from that file (dutch.php) solves the problem. I had the same issue and after removing that one whitespace all worked fine.
