### ISSUE TITLE
CSRFPROTECTOR blocks login from client PC over local network.

### ISSUE THREAD

**Issue by kkoubru** [opendocman/opendocman#258]
Since I have installed the software, I have been facing this issue of not being able to login from client PCs but again login from the server itself. I am being able to sort out the problem till now. Please suggest what should I do to sort out this issue.
Thank you.

**Comment by jrsmith77** [comment]
I have the same issue. I can access it fine from the localhost, but not from a client over the local network. Any suggestions would be great

**Comment by Shiv-Redhat** [comment]
i m also facing same issue OpenDocMan - 403 Access Forbidden by CSRFProtector !

Any suggestions would be great.!!!

**Comment by Shiv-Redhat** [comment]
![image](https://user-images.githubusercontent.com/56635314/66942941-ce99e280-f067-11e9-81f7-afe34a07a618.png)

Issue has been resolved

**Comment by stephenlawrence** [comment]
Base_url is now set automatically.
