### ISSUE TITLE
base_url function

### ISSUE THREAD

**Issue by rorabr** [opendocman/opendocman#278]
Hi!

The base_url function (in functions.php) is computing the wrong URL, if opendocman is installed in a subdirectory from the webserver's root. The consequence was a "Access Forbidden by CSRFProtector!" error being issued right after the login. An early diagnosis can be given by checking if all the elements (css, js, etc) of the index.php page are being loaded (in this case not).

I fixed it by parsing the $_SERVER["REQUEST_URI"] and using it in the sprintf in addition to the SERVER_NAME:

```
function base_url(){
     preg_match('/^(.*)\/[^\/]+$/', isset($_SERVER['REQUEST_URI']) ? $_SERVER['REQUEST_URI'] : "", $m);
     return sprintf(
         "%s://%s%s",
         isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] != 'off' ? 'https' : 'http',
         $_SERVER['SERVER_NAME'], isset($m[1]) ? $m[1] : ""
     );
}
```

Cheers!

**Comment by stephenlawrence** [comment]
Fixed in 1.3.8
