### ISSUE TITLE
OpenDocManager 1.3.7 not installing

### ISSUE THREAD

**Issue by jameswill** [opendocman/opendocman#282]
Hi,

I just tried to make one manual installation on my local windows machine and over centos as well.
However once I enter the database details and then click on install, I get the below mentioned error 👍 
odm Error!: SQLSTATE[HY000] [1045] Access denied for user 'opendocman'@'localhost' (using password: YES) - Please make sure you have created a database

Note: Mysql 5.6 is running and I made a database to connect with named as "odm137".

Can you please check and let me know ?

**Comment by shenlijun** [comment]
this version cannot create config.php properly about database details

**Comment by jameswill** [comment]
Hi,

Yes that is correct.
Any fix on this ?

**Comment by shenlijun** [comment]
do not chown to web user at first(but u need chown templates_c folder )
and when you install from the browser, there will be a message about cannot create config.php
then you can copy its advice,  modify to proper DB info, and write to config.php

now, in your browser, click to next step

**Comment by jameswill** [comment]
Hi,

Sure I did this and later got message config.php already exists and then when I click on next, get the below mentioned error :

Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'odm137.preod_settings' doesn't exist' in /{path}/{to}/odm137/Settings_class.php:83 Stack trace: #0 /{path}/{to}/odm137/Settings_class.php(83): PDOStatement->execute() #1 /{path}/{to}/odm137/odm-init.php(69): Settings->load() #2 /{path}/{to}/odm137/odm-load.php(48): require_once('/publ...') #3 /{path}/{to}/odm137/install/index.php(48): include('/publ...') #4 {main} thrown in /{path}/{to}/odm137/Settings_class.php on line 83

It seems that if this file exists it assumes that the database is there and tries to access the same.

It is that the sql database needs to be imported manually ?
