### ISSUE TITLE
Version 1.3.7 php 7x issue

### ISSUE THREAD

**Issue by iongaroafa** [opendocman/opendocman#283]
Hello, I'm trying to install latest version, but when i access http://xxx.xxx.xxx/odm/ after first page with "create a configuration file", next one is blank... only the logo with OpenDocMan is visible.

So i think this is a php 7x issue because on php5.6 setup it's working fine, but after the instalation is complete when i enter username and password a error is displayed "http error 500"

Could you please check?
Regards,
Ion

**Comment by shenlijun** [comment]
#249

**Comment by shenlijun** [comment]
archive from release page has improper files, download source would be ok

**Comment by stephenlawrence** [comment]
Fixed in 1.3.8
