### ISSUE TITLE
new installation unable to login

### ISSUE THREAD

**Issue by akmalmustajid** [opendocman/opendocman#286]
hi, 
new installation v1.3.7
os win10 xampp. 

successfully installed but unable to login. I have checked the user id and password in the database are correct. 

I also created a new id and new password. still not working. 

how could we check the select statement to verify the user. any modification in index.php to echo $query seems does not working.

**Comment by webby70** [comment]
I have the same problem. opendocman 1.3.7 installation performed successfully by modifying the config.php file with the data for my DB. I use on my server Xampp with Apache/2.4.18 (Win32) OpenSSL/1.0.2e PHP/7.0.1 Vers. client database: libmysql - mysqlnd 5.0.12-dev - 20150407. can someone be able to tell me something about it? Thanks!

**Comment by stephenlawrence** [comment]
@akmalmustajid Please provide additional information on what error you may be seeing or steps we can take to reproduce your issue.
