### ISSUE TITLE
403 Access Forbidden by CSRFProtector!

### ISSUE THREAD

**Issue by bykeda** [opendocman/opendocman#287]
Dears,

While am trying to login after installation of opendocman i get this error "403 Access Forbidden by CSRFProtector!". if anyone can help, please

![image](https://user-images.githubusercontent.com/18286072/87544313-e792fb00-c6ae-11ea-8fd0-68280f87b959.png)
 

![image](https://user-images.githubusercontent.com/18286072/87544366-f9749e00-c6ae-11ea-9456-01595decf44f.png)

**Comment by rantsh** [comment]
I'm having this exact same problem

**Comment by rantsh** [comment]
@bykeda I found the issue, not sure if you still need a solution, anyway, it seems the current opendocman requires to be installed at the document root of the apache vhost, changing this fixes the problem.

For a more technical report:

- `$GLOBALS['CONFIG']['base_url']` needs to include the subfolder where opendocman is installed, but it's clear that the function that populates this variable does not cater for this, see functions.php:

```
function base_url(){
    return sprintf(
        "%s://%s",
        isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] != 'off' ? 'https' : 'http',
        $_SERVER['SERVER_NAME']
    );
}
```

I hope this has been helpful in anyway to someone, I will try to submit a patch to address this later on

**Comment by prbt2016** [comment]
Hello ,

I  am also getting the same issue i.e 403 Access Forbidden by CSRFProtector!. When I debugged the issue, I found that $GLOBALS['CONFIG']['base_url'] in functions.php is not generating the correct URL when installed in a sub-directory. For ex : I try to install via URL i.e : 

http://{domain.com}}/opendocman

Then echoing $GLOBALS['CONFIG']['base_url'], which holds the function base_url() returns url i.e : 

http://{domain.com}} which is wrong url. 

It seems that the function :   

```
function base_url(){
    return sprintf(
        "%s://%s",
        isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] != 'off' ? 'https' : 'http',
        $_SERVER['SERVER_NAME']
    );
}
```

does not have provision for generating the correct URL when installation is made in  a sub-directory.

Please kindly fix this.

**Comment by Kojack-59** [comment]
For info, I fix it by changing 
$_SERVER['SERVER_NAME']

by

$_SERVER['SERVER_NAME']."/your_sub_directory/"

if it can help

**Comment by skyforce97809** [comment]
Hello still i have same mgs
403 Access Forbidden by CASRFProtector
 I have add this line in functions.php
$_SERVER[‘SERVER_NAME’] .”/opendocman/“
Still same massage

**Comment by skyforce97809** [comment]
`
![image](https://user-images.githubusercontent.com/32296261/103150864-be17e880-4791-11eb-9e5b-332a833a08ba.jpg)
`
I am using wamp server window 10

**Comment by skyforce97809** [comment]
![Uploading image.jpg…]()

**Comment by skyforce97809** [comment]
![Uploading image.jpg…]()

**Comment by skyforce97809** [comment]
![BDCED73E-5C59-4204-B6BD-55567F61DFD9](https://user-images.githubusercontent.com/32296261/103150920-6168fd80-4792-11eb-9f88-a5368a7c0fd6.jpeg)

**Comment by webby70** [comment]
hi, i have the same problem but i haven't solved it. i am using xampp on win 2008. 
Apache/2.4.46 (Win64) OpenSSL/1.1.1g PHP/7.4.11
Versione del client del database: libmysql - mysqlnd 7.4.11
Estensione PHP: mysqli 
Versione PHP: 7.4.11
can someone tell me what i can do? thanks.

**Comment by skyforce97809** [comment]
same my brother i am looking for solve this issue

**Comment by skyforce97809** [comment]
> I'm having this exact same problem

How to fix that issue any solution,, what i can add in function.php i have try many time but still stuck on the 403 Access Forbidden by CSRFProtector!

**Comment by niedlipatrik** [comment]
I had the same problem, I managed to solve it by creating a folder with editing permission in a different location on the example server: "public_html/edoc21/odm_data" and put this path in the database in the table "odm_settings" field "dataDir"
Now it is working, by default the installation creates a folder to which we do not have access and even if we point to the installation it seems that it does not write to the database.

**Comment by arjantenhoopen** [comment]
Same problem here, installed in http://localhost/opendocman where opendocman is a virtual directory.
All tips and tricks to solve this are appreciated!

**Comment by niedlipatrik** [comment]
Hello.
I put the quotes. example: "$_SERVER['SERVER_NAME']" . "/opendocman"

**Comment by stephenlawrence** [comment]
There are a couple issues going on here: 

1. The base_url() function was not using the proper server variables to build the url
2. The forgot password page was not displaying the header/footer so it was not getting the proper javascripts loaded

**Comment by stephenlawrence** [comment]
@bykeda  Please let me know if 1.3.8 resolves any of your issues.
