### ISSUE TITLE
first installation: after insertion of admin, pw: 403 Access Forbidden by CSRFProtector

### ISSUE THREAD

**Issue by sunInForest** [opendocman/opendocman#291]
issue described in the title.

not working:
- increasing in both php.ini (cli, apache2) the upload size
- adding into the table 'settings' a row, name: base_url

.. because:
the base_url is taken from function base_url() in function.php. Problem: the server-name (instead of the servername & base-url) is returned. Resolution: changing the return value to the hard-coded base url. - not a good solution but quick and it works.

... writing this b/c other suggestions did not work, maybe somebody will search for this issue also.

**Comment by fossphur** [comment]
I'm having this exact issue and had found that upload size suggestion and that it didn't work. Any chance you could paste an example of what your change looks like? I thought I understood what you meant and tried doing it but I am still stuck in 403 Access Forbidden land. Wish I could just turn CSRF off.

**Comment by jiannis99** [comment]
What i must to add in base_url row?

**Comment by Kojack-59** [comment]
please check #287

**Comment by stephenlawrence** [comment]
@sunInForest Please let me know if 1.3.8 resolves your issue?

**Comment by DerKaffeeschluerfer** [comment]
Hello @stephenlawrence 
I've the same problem. I've put ODM on my webspace and started the installation. I've put the credentials for the database into the fields but it wouldn't write to the config file. The next step brings the message "Error!: SQLSTATE[28000] [1045] Access denied for user 'opendocman'@'localhost' (using password: YES) - Please make sure you have created a database" the DB is created. In the message are not the correct user, DB-Name and  the ODM-Folder ist writeble and the config.php-file too. When I put the credentals manually into the config file I'll get the CSRF message.

Hope you can help!
Stephen

**Comment by stephenlawrence** [comment]
@DerKaffeeschluerfer If the config file cannot be written to by the PHP code then you will see that message since it defaults to opendocman user if the config.php was not read. Did the app give you a message about your config.php file not being writeable?

**Comment by DerKaffeeschluerfer** [comment]
@stephenlawrence No, the config file is writeable and I got no message that's not

**Comment by stephenlawrence** [comment]
@DerKaffeeschluerfer Create a new issue for this so we can have a conversation there. This issue re: CSRF is being closed.
