### ISSUE TITLE
Database configuration won't be written to config.php file

### ISSUE THREAD

**Issue by DerKaffeeschluerfer** [opendocman/opendocman#296]
Hello @stephenlawrence 
I've the same problem. I've put ODM on my webspace and started the installation. I've put the credentials for the database into the fields but it wouldn't write to the config file. The next step brings the message "Error!: SQLSTATE[28000] [1045] Access denied for user 'opendocman'@'localhost' (using password: YES) - Please make sure you have created a database" the DB is created. In the message are not the correct user, DB-Name and  the ODM-Folder ist writeble and the config.php-file too. When I put the credentals manually into the config file I'll get the CSRF message.

Hope you can help!
Stephen

_Originally posted by @DerKaffeeschluerfer in https://github.com/opendocman/opendocman/issues/291#issuecomment-772559260_

**Comment by stephenlawrence** [comment]
Ok, lets verify that the config.php file can be written:

near the bottom of install/setup-config.php you should see something like this:
```
if (! is_writable(ABSPATH)) {
```

Change that to be 
```
if (! is_writable(ABSPATH . 'config.php')) {
```

When you reload the page lets see if a message pops up.

**Comment by DerKaffeeschluerfer** [comment]
Now i get this:

Sorry, we were unable to write to the templates_c folder. You will need to make sure that /hp/bv/ab/gd/www/doc//templates_c is writable by the web server

**Comment by stephenlawrence** [comment]
Ok, it seems like your files on www/ are not writeable by your web user. 

You can also try this to verify:

Create a new filetest.php file and upload it to your www/doc folder:
```
<?php 
 $File = "YourFile.txt"; 
 $Handle = fopen($File, 'w');
 ?>
```

When you visit http://XXXX/doc/filetest.php in your browser see if the fopen throws an error.

**Comment by DerKaffeeschluerfer** [comment]
The file is added to the folder.

-rw-r--r--  1 ftp2*********** users       0 Feb  3 16:24 YourFile.txt
I've changed the username

**Comment by stephenlawrence** [comment]
ok, please show a full list of the files in your /doc folder with the user:group and permissions on each.

**Comment by DerKaffeeschluerfer** [comment]
Here it is
[folder.txt](https://github.com/opendocman/opendocman/files/5919606/folder.txt)

**Comment by stephenlawrence** [comment]
Ok, and to verify, are you using the latest code from the master branch? 

Let's start over again with fresh installation of files (from the current master branch). When you get to any page that has any warnings, please report back here.

**Comment by DerKaffeeschluerfer** [comment]
yes, I cloned it today from git

**Comment by stephenlawrence** [comment]
Ok, I just pushed a small typo for the templates_c check.

**Comment by DerKaffeeschluerfer** [comment]
ok I start again ;-)

**Comment by DerKaffeeschluerfer** [comment]
Sorry, it doesn't work. Same again

**Comment by stephenlawrence** [comment]
Ok, what page is the error happening on, and what exactly does the error say?

**Comment by DerKaffeeschluerfer** [comment]
yes!

Error!: SQLSTATE[28000] [1045] Access denied for user 'opendocman'@'localhost' (using password: YES) - Please make sure you have created a database

**Comment by stephenlawrence** [comment]
What are you doing that causes this error? Are submitting the form on the setup-config.php page? I need a little more detail for this. That error is coming from a database call somewhere but I really need to know what line is throwing that. Do you have php error logs you can look at?

**Comment by stephenlawrence** [comment]
Also, did config.php get written with the proper values?

**Comment by DerKaffeeschluerfer** [comment]
I put the credentials for database and admin user to the configuration form and go to the next step. Then I'll run the installation

**Comment by DerKaffeeschluerfer** [comment]
The correct values are not in the configuration file

**Comment by stephenlawrence** [comment]
Ok, so looking at that code it does a DB connection test first before creating the config.php file. On line 201 add this for debug output:

```
print_r($_POST);exit;
```

That should show you what values are being submitted on the form and what the DB values will be right before the db test.

**Comment by DerKaffeeschluerfer** [comment]
I only have 66 lines in my config.php file

**Comment by DerKaffeeschluerfer** [comment]
I don't have access to the error logs. I can contact the support team to get them

**Comment by DerKaffeeschluerfer** [comment]
ok. I got the output with the correct values

**Comment by DerKaffeeschluerfer** [comment]
The output are the correct values

**Comment by stephenlawrence** [comment]
DSN is data source name which the PDO library uses as a connection string.

**Comment by DerKaffeeschluerfer** [comment]
dsn=mysql:host=mysql.webhosting51.1blu.de;dbname=db294315x3069207;charset=utf8, DB_USER=s294315_3069207, DB_PASS=XXXXXXXXXXXX

**Comment by stephenlawrence** [comment]
Ok great, and did the app end up writing out the config.php file with the same values?

**Comment by DerKaffeeschluerfer** [comment]
No, the script exits after the output of the values. When I comment the echo code the config.php file will be generated without the correct values

**Comment by DerKaffeeschluerfer** [comment]
Great! You've made it through this part of the installation. OpenDocMan can now communicate with your database. If you are ready, time now to…
When I go to the next step I'll get the error from the first post

**Comment by stephenlawrence** [comment]
Ok, I think I found the issue.

in config-sample.php please changes these lines (see the new values at the end of each line):

```
    $db_name = isset($_ENV['DB_NAME']) ? $_ENV['DB_NAME'] : 'database_name_here';
    $db_user = isset($_ENV['DB_USER']) ? $_ENV['DB_USER'] : 'username_here';
    $db_pass = isset($_ENV['DB_PASS'])? $_ENV['DB_PASS'] : 'password_here';
    $db_host = isset($_ENV['DB_HOST']) ? $_ENV['DB_HOST'] : 'localhost';
```

Make that change, remove your config.php, then re-run the installer.

**Comment by DerKaffeeschluerfer** [comment]
Should I put my values into the line in the config-sample file or copy the complete code?

**Comment by stephenlawrence** [comment]
the complete code. Those values on the end are searched for and replaced with the right values when setup-config.php writes the file.

**Comment by DerKaffeeschluerfer** [comment]
Error!: SQLSTATE[28000] [1045] Access denied for user 'username_here'@'localhost' (using password: YES) - Please make sure you have created a database

**Comment by DerKaffeeschluerfer** [comment]
Same again :-(

**Comment by stephenlawrence** [comment]
Sorry, make sure you make the changes to the config-sample.php file, not config.php. You would remove the config.php and re-run the install from the beginning.

**Comment by DerKaffeeschluerfer** [comment]
Yes, I did it so

**Comment by DerKaffeeschluerfer** [comment]
I think that the replacement will not work

**Comment by stephenlawrence** [comment]
Ok, could you send an email to info@opendocman.com w/ hosting user login information and URL of the app so I can login to the filesystem and troubleshoot further?

**Comment by DerKaffeeschluerfer** [comment]
Sorry, I can give you a remote session and open the connection but I can not give the login data away

**Comment by stephenlawrence** [comment]
@DerKaffeeschluerfer Try branch 296-config-file-not-correct

**Comment by DerKaffeeschluerfer** [comment]
@stephenlawrence you're awesome! I'll try it now. and come back

**Comment by DerKaffeeschluerfer** [comment]
A complete new try. New git clone, new database. Configuration form is ok, the database has been generated. After the first login I got this white page.
![grafik](https://user-images.githubusercontent.com/78486512/106874856-5761e500-66d6-11eb-8555-be6967fefe13.png)
When I try a new login I get this white page.
![grafik](https://user-images.githubusercontent.com/78486512/106876257-d0ae0780-66d7-11eb-9f32-baecf32aa480.png)
