### ISSUE TITLE
OpenDocMan 1.4.0 throws Fatal error after logging in

### ISSUE THREAD

**Issue by prbt2016** [opendocman/opendocman#301]
Hello,

I was in the process of manual installation of OpenDocMan version 1.4.0 on Centos 6.9 Final Linux with PHP 5.4, MYSQL 5.5.62, Apache 2.2.34.

However I encountered with an error post successful manual installation i.e after logging into the admin panel gives the following fatal error i.e : 

` Fatal error: Call to undefined method databaseData::databaseData() in /{{PATH}}/{{TO}}/{ODM}}/User_class.php on line 52`

What could be causing this issue?. 

Could you please replicate this at your end and resolve this?.

**Comment by stephenlawrence** [comment]
Fix coming up
