### ISSUE TITLE
CAN'T DROP CONSTRAINT 'name'

### ISSUE THREAD

**Issue by popati363** [opendocman/opendocman#305]
This error is coming up, despite several attempts to re-install

Updating from DB versions 1.3.6...
Altering the data table...
Altering the settings table...

Fatal error: Uncaught PDOException: SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP CONSTRAINT `name`; check that it exists in C:\xampp\htdocs\opendocman\install\upgrade_136.php:36 Stack trace: #0 C:\xampp\htdocs\opendocman\install\upgrade_136.php(36): PDOStatement->execute() #1 C:\xampp\htdocs\opendocman\install\index.php(449): include('C:\\xampp\\htdocs...') #2 C:\xampp\htdocs\opendocman\install\index.php(306): do_update_136() #3 {main} thrown in C:\xampp\htdocs\opendocman\install\upgrade_136.php on line 36

**Comment by stephenlawrence** [comment]
@popati363  Do you know if this was this an upgrade from 1.3.6, or an earlier version?

**Comment by popati363** [comment]
Hi Stephenlawrence, this was an upgrade from 1.3.6 to 1.4.0

**Comment by stephenlawrence** [comment]
In the upgrade_136.php file can you try and replace `DROP CONSTRAINT` with `DROP INDEX` and try again.
