### ISSUE TITLE
I can't get past the Login.

### ISSUE THREAD

**Issue by Jendale** [opendocman/opendocman#307]
![image](https://user-images.githubusercontent.com/28188970/111194831-8bde9000-85f6-11eb-878b-c16dfa359c51.png)
What am I missing?

![image](https://user-images.githubusercontent.com/28188970/111195145-eaa40980-85f6-11eb-9f5c-db5e457a209e.png)
I created the database correctly and imported the database.sql on my xampp.

**Comment by stephenlawrence** [comment]
Hello, 

 
Few things to try:
- Please check your PHP error logs
- Let us know which version of OpenDocMan you are running
- Verify there is a user on the odm_user table
- Enable allow_password_reset in the odm_settings table and reset the password for the user

**Comment by Jendale** [comment]
@stephenlawrence I got it. Thanks :)
