### ISSUE TITLE
Fresh install issues, language issue

### ISSUE THREAD

**Issue by tkalfaoglu** [opendocman/opendocman#314]
1) README says admin/blank but that gives an error when trying to log in - I edited the password using phpmyadmin and was able to login.
2) Not obvious which dirs should be writeable by the web server. I changed the permissions based on the errors I get.
3) When language is set to Turkish, it displays ampercents and other cryptic characters. 
For example it says "bulunamad & # 305 ; " (spaces added by me)  whereas it should say "bulunamadı"
FIXED: The translation must have been done without using UTF-8. I have the new translation attached with ALL text translated too.

**Comment by tkalfaoglu** [comment]
[turkish.txt](https://github.com/opendocman/opendocman/files/6252468/turkish.txt)

**Comment by stephenlawrence** [comment]
Resolved the turkish lang issues. 

Updated the README.md for the manual password instruction

Re: the data directory. The readme does have a little documentation on this as well as the installer splash page that document various web server settings. If possible, can you point specifically to where those might be improved?
