### ISSUE TITLE
File type XLSX is not currently supported in 1.2.6.5 version

### ISSUE THREAD

**Issue by Hiden** [opendocman/opendocman#84]
In case I add XLSX document, OpenDocMan repots this message (but all document types are allowed and this was in previous version working):

That file type is not currently supported.
Please upload a document conforming to any of the following file types or add the missing MIMETYPE to Admin->Settings->allowedFileTypes

**Comment by apmuthu** [comment]
Incorporated and fixed in:
https://github.com/opendocman/opendocman/commit/f3a457d07f258d0309ae5d47b3ef7920fc4a131e

**Comment by apmuthu** [comment]
If and where is this fixed in the master branch here?

**Comment by stephenlawrence** [comment]
I believe this was resolved by adding application/x-zip-compressed to the default filetypes.

**Comment by apmuthu** [comment]
No. It was fixed by the addition of:
````INSERT INTO `odm_filetypes` VALUES(NULL, 'application/x-zip', 1);```` in
https://github.com/opendocman/opendocman/commit/f3a457d07f258d0309ae5d47b3ef7920fc4a131e
but needs to be incorporated into the master back again - got removed somewhere in between.
